services:

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - JWT_SECRET=AYqQdMQcnW6JOCMyBS24A8GFbeRk4VTth6o8FlSDNIs
      - JWT_EXPIRATION=86400000
    ports:
      - "8055:8055"
    volumes:
      - ./:/app