spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

orbytum:
  mail:
    from: ${ORBYTUM_MAIL_FROM:${spring.mail.username}}
    from-name: ${ORBYTUM_MAIL_FROM_NAME:Orbytum}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

security:
  password:
    saltLength: 16
    hashLength: 32
    parallelism: 1
    memory: 16384
    iterations: 2

logging:
  level:
    org.hibernate.orm.results: TRACE