spring:
  application:
    name: api
  datasource:
    url: ${JDBC_URL}
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

security:
  password:
    saltLength: 16
    hashLength: 32
    parallelism: 1
    memory: 16384
    iterations: 2

logging:
  level:
    org.hibernate.orm.results: TRACE