CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE atividade
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    projeto_id    BIGINT,
    titulo        VARCHAR(255)                            NOT NULL,
    descricao     VARCHAR(255)                            NOT NULL,
    status        SMALLINT,
    dth_prazo     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_conclusao TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_registro  date                                    NOT NULL,
    is_ativo      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_atividade PRIMARY KEY (id)
);

CREATE TABLE convite
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grupo_id      BIGINT,
    dth_expiracao TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_registro  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_convite PRIMARY KEY (id)
);

CREATE TABLE credenciais_login
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    senha        VARCHAR(255)                            NOT NULL,
    is_ativo     BOOLEAN                                 NOT NULL,
    access_level VARCHAR(255),
    criador_id   BIGINT,
    CONSTRAINT pk_credenciaislogin PRIMARY KEY (id)
);

CREATE TABLE documento
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255)                            NOT NULL,
    extensao  VARCHAR(255)                            NOT NULL,
    documento OID                                     NOT NULL,
    CONSTRAINT pk_documento PRIMARY KEY (id)
);

CREATE TABLE edital
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo           VARCHAR(255)                            NOT NULL,
    descricao        VARCHAR(255)                            NOT NULL,
    url              VARCHAR(255)                            NOT NULL,
    valor            DECIMAL,
    dth_abertura     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_encerramento TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_edital PRIMARY KEY (id)
);

CREATE TABLE editalxprojeto
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    edital_id  BIGINT,
    projeto_id BIGINT,
    is_ativo   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_editalxprojeto PRIMARY KEY (id)
);

CREATE TABLE evento
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo       VARCHAR(255)                            NOT NULL,
    descricao    VARCHAR(255)                            NOT NULL,
    is_online    BOOLEAN                                 NOT NULL,
    url          VARCHAR(255),
    localizacao  VARCHAR(255),
    dth_inicio   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_fim      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_registro TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_evento PRIMARY KEY (id)
);

CREATE TABLE grupo
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255)                            NOT NULL,
    is_ativo BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_grupo PRIMARY KEY (id)
);

CREATE TABLE grupoxusuario
(
    id         UUID    NOT NULL,
    grupo_id   BIGINT,
    usuario_id BIGINT,
    role_id    BIGINT,
    is_ativo   BOOLEAN NOT NULL,
    CONSTRAINT pk_grupoxusuario PRIMARY KEY (id)
);

CREATE TABLE material
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome          VARCHAR(255)                            NOT NULL,
    descricao     VARCHAR(255)                            NOT NULL,
    identificador VARCHAR(255)                            NOT NULL,
    quantidade    INTEGER                                 NOT NULL,
    localizacao   VARCHAR(255)                            NOT NULL,
    status        INTEGER,
    dth_compra    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_registro  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_material PRIMARY KEY (id)
);

CREATE TABLE material_emprestimo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    material_id  BIGINT,
    grupo_id     BIGINT,
    quantidade   INTEGER                                 NOT NULL,
    is_devolvido BOOLEAN                                 NOT NULL,
    dth_inicio   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_fim      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_materialemprestimo PRIMARY KEY (id)
);

CREATE TABLE material_emprestimo_solicitacao
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id      UUID,
    justificativa   VARCHAR(255)                            NOT NULL,
    is_interna      BOOLEAN                                 NOT NULL,
    is_aprovada     BOOLEAN                                 NOT NULL,
    dth_solicitacao TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dth_resposta    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_materialemprestimosolicitacao PRIMARY KEY (id)
);

CREATE TABLE material_emprestimo_solicitacao_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    material_id BIGINT,
    quantidade  INTEGER                                 NOT NULL,
    CONSTRAINT pk_materialemprestimosolicitacaoitem PRIMARY KEY (id)
);

CREATE TABLE material_emprestimo_solicitacao_items
(
    material_emprestimo_solicitacao_id BIGINT NOT NULL,
    items_id                           BIGINT NOT NULL
);

CREATE TABLE projeto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grupo_id     BIGINT,
    status       INTEGER,
    titulo       VARCHAR(255)                            NOT NULL,
    assunto      VARCHAR(255)                            NOT NULL,
    dth_registro TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_projeto PRIMARY KEY (id)
);

CREATE TABLE publicacao
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo       VARCHAR(255)                            NOT NULL,
    descricao    VARCHAR(255)                            NOT NULL,
    projeto_id   BIGINT,
    url          VARCHAR(255)                            NOT NULL,
    dth_registro TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo     BOOLEAN                                 NOT NULL,
    documento_id BIGINT,
    CONSTRAINT pk_publicacao PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE rolexpermissao
(
    role_id    BIGINT NOT NULL,
    permissoes VARCHAR(255)
);

CREATE TABLE usuario
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome                 VARCHAR(255)                            NOT NULL,
    email                VARCHAR(255)                            NOT NULL,
    telefone             VARCHAR(255)                            NOT NULL,
    titulo               VARCHAR(255)                            NOT NULL,
    dth_registro         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo             BOOLEAN                                 NOT NULL,
    credenciais_login_id BIGINT,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE material_emprestimo_solicitacao_items
    ADD CONSTRAINT uc_material_emprestimo_solicitacao_items_items UNIQUE (items_id);

ALTER TABLE publicacao
    ADD CONSTRAINT uc_publicacao_documentoid UNIQUE (documento_id);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_credenciaisloginid UNIQUE (credenciais_login_id);

ALTER TABLE atividade
    ADD CONSTRAINT FK_ATIVIDADE_ON_PROJETO FOREIGN KEY (projeto_id) REFERENCES projeto (id);

ALTER TABLE convite
    ADD CONSTRAINT FK_CONVITE_ON_GRUPO FOREIGN KEY (grupo_id) REFERENCES grupo (id);

ALTER TABLE credenciais_login
    ADD CONSTRAINT FK_CREDENCIAISLOGIN_ON_CRIADORID FOREIGN KEY (criador_id) REFERENCES usuario (id);

ALTER TABLE editalxprojeto
    ADD CONSTRAINT FK_EDITALXPROJETO_ON_EDITAL FOREIGN KEY (edital_id) REFERENCES edital (id);

ALTER TABLE editalxprojeto
    ADD CONSTRAINT FK_EDITALXPROJETO_ON_PROJETO FOREIGN KEY (projeto_id) REFERENCES projeto (id);

ALTER TABLE grupoxusuario
    ADD CONSTRAINT FK_GRUPOXUSUARIO_ON_GRUPO FOREIGN KEY (grupo_id) REFERENCES grupo (id);

ALTER TABLE grupoxusuario
    ADD CONSTRAINT FK_GRUPOXUSUARIO_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE grupoxusuario
    ADD CONSTRAINT FK_GRUPOXUSUARIO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);

ALTER TABLE material_emprestimo_solicitacao_item
    ADD CONSTRAINT FK_MATERIALEMPRESTIMOSOLICITACAOITEM_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES material (id);

ALTER TABLE material_emprestimo_solicitacao
    ADD CONSTRAINT FK_MATERIALEMPRESTIMOSOLICITACAO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES grupoxusuario (id);

ALTER TABLE material_emprestimo
    ADD CONSTRAINT FK_MATERIALEMPRESTIMO_ON_GRUPO FOREIGN KEY (grupo_id) REFERENCES grupo (id);

ALTER TABLE material_emprestimo
    ADD CONSTRAINT FK_MATERIALEMPRESTIMO_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES material (id);

ALTER TABLE projeto
    ADD CONSTRAINT FK_PROJETO_ON_GRUPO FOREIGN KEY (grupo_id) REFERENCES grupo (id);

ALTER TABLE publicacao
    ADD CONSTRAINT FK_PUBLICACAO_ON_DOCUMENTOID FOREIGN KEY (documento_id) REFERENCES documento (id);

ALTER TABLE publicacao
    ADD CONSTRAINT FK_PUBLICACAO_ON_PROJETO FOREIGN KEY (projeto_id) REFERENCES projeto (id);

ALTER TABLE usuario
    ADD CONSTRAINT FK_USUARIO_ON_CREDENCIAISLOGINID FOREIGN KEY (credenciais_login_id) REFERENCES credenciais_login (id);

ALTER TABLE material_emprestimo_solicitacao_items
    ADD CONSTRAINT fk_matempsolite_on_material_emprestimo_solicitacao FOREIGN KEY (material_emprestimo_solicitacao_id) REFERENCES material_emprestimo_solicitacao (id);

ALTER TABLE material_emprestimo_solicitacao_items
    ADD CONSTRAINT fk_matempsolite_on_material_emprestimo_solicitacao_item FOREIGN KEY (items_id) REFERENCES material_emprestimo_solicitacao_item (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);

ALTER TABLE rolexpermissao
    ADD CONSTRAINT fk_rolexpermissao_on_role FOREIGN KEY (role_id) REFERENCES role (id);