ALTER TABLE conviteGrupo ADD COLUMN IF NOT EXISTS role_id BIGINT;
ALTER TABLE conviteGrupo ADD COLUMN IF NOT EXISTS limite_uso INTEGER;
ALTER TABLE conviteGrupo ADD COLUMN IF NOT EXISTS usos INTEGER DEFAULT 0;
ALTER TABLE conviteGrupo ADD COLUMN IF NOT EXISTS token VARCHAR(255);
ALTER TABLE conviteGrupo ADD COLUMN IF NOT EXISTS tipo VARCHAR(255);
ALTER TABLE conviteGrupo ADD COLUMN IF NOT EXISTS usuario_convidado_id BIGINT;
ALTER TABLE conviteGrupo ADD COLUMN IF NOT EXISTS usuario_remetente_id BIGINT;

ALTER TABLE conviteGrupo DROP CONSTRAINT IF EXISTS FK_CONVITE_ON_ROLE;
ALTER TABLE conviteGrupo ADD CONSTRAINT FK_CONVITE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);
