CREATE TABLE IF NOT EXISTS lembrete
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo            VARCHAR(255)                            NOT NULL,
    descricao         TEXT,
    tipo              VARCHAR(50)                             NOT NULL,
    data_hora         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    localizacao       VARCHAR(255),
    link              VARCHAR(255),
    recorrencia       VARCHAR(50)                             NOT NULL DEFAULT 'NENHUMA',
    grupo_id          BIGINT                                  NOT NULL,
    organizador_id    BIGINT                                  NOT NULL,
    ata_key           VARCHAR(512),
    ata_nome_original VARCHAR(255),
    dth_criacao       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_ativo          BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_lembrete PRIMARY KEY (id),
    CONSTRAINT fk_lembrete_grupo FOREIGN KEY (grupo_id) REFERENCES grupo (id),
    CONSTRAINT fk_lembrete_organizador FOREIGN KEY (organizador_id) REFERENCES usuario (id)
);

CREATE TABLE IF NOT EXISTS lembrete_participante
(
    lembrete_id BIGINT NOT NULL,
    usuario_id  BIGINT NOT NULL,
    CONSTRAINT pk_lembrete_participante PRIMARY KEY (lembrete_id, usuario_id),
    CONSTRAINT fk_lembrete_part_lembrete FOREIGN KEY (lembrete_id) REFERENCES lembrete (id) ON DELETE CASCADE,
    CONSTRAINT fk_lembrete_part_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);
