CREATE TABLE IF NOT EXISTS projeto_x_usuario
(
    id         UUID    NOT NULL,
    projeto_id BIGINT,
    usuario_id BIGINT,
    nivel      VARCHAR(20),
    is_ativo   BOOLEAN NOT NULL,
    CONSTRAINT pk_projeto_x_usuario PRIMARY KEY (id)
);

ALTER TABLE projeto_x_usuario DROP CONSTRAINT IF EXISTS FK_PROJETOXUSUARIO_ON_PROJETO;
ALTER TABLE projeto_x_usuario ADD CONSTRAINT FK_PROJETOXUSUARIO_ON_PROJETO FOREIGN KEY (projeto_id) REFERENCES projeto (id);

ALTER TABLE projeto_x_usuario DROP CONSTRAINT IF EXISTS FK_PROJETOXUSUARIO_ON_USUARIO;
ALTER TABLE projeto_x_usuario ADD CONSTRAINT FK_PROJETOXUSUARIO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);

ALTER TABLE projeto ADD COLUMN IF NOT EXISTS is_inicial BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE projeto ADD COLUMN IF NOT EXISTS is_favorito BOOLEAN NOT NULL DEFAULT false;
