ALTER TABLE atividade ADD COLUMN IF NOT EXISTS responsavel_id BIGINT;
ALTER TABLE atividade ADD COLUMN IF NOT EXISTS atividade_pai_id BIGINT;

ALTER TABLE atividade ALTER COLUMN dth_conclusao DROP NOT NULL;
ALTER TABLE atividade ALTER COLUMN dth_registro TYPE TIMESTAMP WITHOUT TIME ZONE USING dth_registro::timestamp;

ALTER TABLE atividade DROP CONSTRAINT IF EXISTS FK_ATIVIDADE_ON_RESPONSAVEL;
ALTER TABLE atividade ADD CONSTRAINT FK_ATIVIDADE_ON_RESPONSAVEL FOREIGN KEY (responsavel_id) REFERENCES usuario (id);

ALTER TABLE atividade DROP CONSTRAINT IF EXISTS FK_ATIVIDADE_ON_ATIVIDADEPAI;
ALTER TABLE atividade ADD CONSTRAINT FK_ATIVIDADE_ON_ATIVIDADEPAI FOREIGN KEY (atividade_pai_id) REFERENCES atividade (id);

-- Conversao dos status legados para o novo fluxo:
-- A_FAZER(1) -> PENDENTE(1) | EM_ANDAMENTO(2) -> EM_ANDAMENTO(2)
-- FINALIZADA(3) -> CONCLUIDA(4) | TRAVADA(4) -> EM_ANDAMENTO(2)
UPDATE atividade SET status = 2 WHERE status = 4;
UPDATE atividade SET status = 4 WHERE status = 3;
